### ISSUE TITLE
# Refactor API Guide: QE checklist

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-monitoring#2]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the `make clean html` command to build chunked content. 
- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the _API reference_ section to verify that the methods for each resource are in a single topic.
- [x] Check the _General API information_ topics to make sure they match the common content where possible.
- [x] Check the _Authentication_ topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check `conf.py` to make sure it has the updates from the 
     [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
Item 1. Strider build clean.

**Comment by cyrichardson** [comment]
Item 3. Navigation matched API Guide template, with the addition of the Technical Reference.

**Comment by cyrichardson** [comment]
Item 4. They are in a single topic, but you might want to make the following changes:
- Do you want to change maxdepth in main monitoring index to 3? That is what the template uses. It might help the left nav for the API reference section in the staging output.
- Also, entity operations might be a the wrong heading level??? They don't show up under Entities operations, but at the same level as Entities.

**Comment by cyrichardson** [comment]
Item 5. Follows template for General API information topics, with the addition of Time series collections and Audits.

**Comment by cyrichardson** [comment]
Item 6. Authentication section follows the template, with the inclusion of the Raxmon client authentication at the end.

**Comment by cyrichardson** [comment]
Item 7. conf.py matches new template.

**Comment by cyrichardson** [comment]
Item 8. Copied meker12 master to branch in my local clone. make clean html build is clean.

**Comment by cyrichardson** [comment]
Item 2. Link checking - all links checked manually: 
- In Concepts section - under Monitoring agent, the Agent check types link gives 404.
- There are several references to the "Cloud Intelligence control panel" or the "Cloud Intelligence interface". These are redirected to the standard Cloud Control Panel and won't let you get back to the docs. Not broken  - just wonder about the behavior.
- If you search for docs.rackspace.com in the api-docs folder, you will find a few occurrences. These links don't appear to be broken, but they take to you  the top of the Cloud Monitoring documentation, not to the location of the topic in the docs.

**Comment by cyrichardson** [comment]
@meker QE done. Just found the things noted in our Slack convo and then also the last comment above about links.

**Comment by meker12** [comment]
Thank you!

**Comment by cyrichardson** [comment]
@meker12 Glad to help!
